# Generated by Django 3.0.4 on 2020-04-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('abreviacao', models.CharField(help_text='Máximo 3 letras', max_length=3, verbose_name='Abreviação')),
                ('matriz', models.CharField(help_text='Ano de aprovação de matriz do curso', max_length=4)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
    ]
