# Generated by Django 3.0.4 on 2020-04-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da disciplina')),
            ],
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-is_active', 'nome']},
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semestre', models.CharField(choices=[('PEN', 'Pendente'), ('OPT', 'Optativa'), ('1', '1º Semestre'), ('2', '2º Semestre'), ('3', '3º Semestre'), ('4', '4º Semestre'), ('5', '5º Semestre'), ('6', '6º Semestre'), ('7', '7º Semestre'), ('8', '8º Semestre'), ('9', '9º Semestre'), ('10', '10º Semestre')], default='PEN', max_length=3)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ManyToManyField(through='curso.Semestre', to='curso.Curso', verbose_name='Curso'),
        ),
    ]
