# Generated by Django 3.0.4 on 2020-04-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20200414_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Código'),
        ),
    ]
