# Generated by Django 3.0.5 on 2020-05-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_auto_20200519_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ManyToManyField(to='curso.Curso'),
        ),
    ]
