# Generated by Django 3.0.5 on 2020-05-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_auto_20200519_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome', 'codigo']},
        ),
        migrations.AlterField(
            model_name='curso',
            name='matriz',
            field=models.CharField(help_text='Ano de aprovação da matriz do curso', max_length=4),
        ),
    ]
