# Generated by Django 3.0.4 on 2020-04-15 17:32

import cc.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0003_auto_20200414_1337'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(blank=True, help_text='O candidato deve explicar os motivos para solicitar a prova, por exemplo: experiência profissional, cursos não regulares, aproveitamentos indeferidos, entre outros.', null=True, verbose_name='Justificativa para o pedido')),
                ('documentos', models.FileField(blank=True, null=True, upload_to=None, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documentos comprobatorios de conhecimentos')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('cursou_anteriormente', models.BooleanField(blank=True, null=True, verbose_name='Cursou anteriormente a disciplina solicitada')),
                ('homologada', models.BooleanField(blank=True, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Disciplina')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_solicitacao', 'solicitante'],
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[cc.models.validate_nota])),
                ('ausente', models.BooleanField(default=False)),
                ('resultado', models.CharField(blank=True, choices=[('APR', 'Aprovado'), ('REP', 'Reprovado'), ('AUS', 'Ausente'), ('PEN', 'Pendente')], default='PEN', max_length=3)),
                ('data_resultado', models.DateTimeField(auto_now_add=True, verbose_name='Data do resultado')),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cc.Solicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(verbose_name='')),
                ('documentos', models.FileField(blank=True, null=True, upload_to=None, verbose_name='Documentos comprobatorios da justificativa')),
                ('data_solicitacao_recurso', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação do recurso')),
                ('resultado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cc.Resultado')),
            ],
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.UniqueConstraint(fields=('solicitante', 'disciplina'), name='unique_solicitação'),
        ),
    ]
