# Generated by Django 3.0.4 on 2020-04-15 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to=None, validators=[django.core.validators.FileExtensionValidator(['.pdf'])], verbose_name='Documentos comprobatorios de conhecimentos'),
        ),
    ]
