# Generated by Django 3.0.5 on 2020-04-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_auto_20200415_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='homologada',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('HOM', 'Homologado'), ('NOH', 'Não Homologado')], default='PEN', max_length=3),
        ),
    ]
