# Generated by Django 3.0.5 on 2020-04-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_auto_20200422_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['semestre_solicitacao', 'solicitante']},
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='homologada',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('SIM', 'Homologado'), ('NAO', 'Não Homologado')], default='PEN', max_length=3),
        ),
    ]
