# Generated by Django 3.0.5 on 2020-05-01 01:19

import cc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_auto_20200423_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['semestre_solicitacao', 'solicitante', 'disciplina']},
        ),
        migrations.AddField(
            model_name='resultado',
            name='nota_anterior',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[cc.models.validate_nota]),
        ),
        migrations.AddField(
            model_name='resultado',
            name='resultado_recurso',
            field=models.CharField(blank=True, choices=[('DEF', 'Deferido'), ('IND', 'Indeferido')], max_length=3),
        ),
        migrations.AddField(
            model_name='resultado',
            name='solicitar_recurso',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Recurso',
        ),
    ]
