# Generated by Django 3.0.5 on 2020-05-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_auto_20200430_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='solicitar_recurso',
            new_name='solicitar_recurso',
        ),
    ]
