# Generated by Django 3.0.5 on 2020-05-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-matricula', 'nome_completo'], 'permissions': [('can_add_avaliador', 'Pode atribuir avaliador a solicitacao')], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
